apiVersion: v1
kind: Service
metadata:
  name: nocodb-svc
  namespace: nocodb
spec:
  ports:
    - name: nocodb-app-webui
      port: 8080
      targetPort: 8080
  selector:
    app: nocodb-app-webui


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nocodb-deployment
  namespace: nocodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nocodb-app-webui
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: nocodb-app-webui
    spec:
      restartPolicy: Always
      volumes:
      - name: nocodb-claim0
        persistentVolumeClaim:
          claimName: nocodb-fs-pvc
      initContainers:
        - name: wait-for-postgres
          image: busybox:1.36
          command: ['sh', '-c']
          args:
          - |
            echo "Waiting for PostgreSQL to be ready..."
            until nc -zv postgres-0.postgres-svc.nocodb-app.svc.cluster.local 5432; do
              echo "PostgreSQL not ready yet, sleeping for 5s..."
              sleep 5
            done
            echo "PostgreSQL is ready!"

          env:
          - name: PG_USER
            valueFrom:
              secretKeyRef:
                name: postgres-credentials
                key: POSTGRES_USER
          - name: PG_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres-credentials
                key: POSTGRES_PASSWORD
          - name: PG_DB
            valueFrom:
              secretKeyRef:
                name: postgres-credentials
                key: POSTGRES_DB
      containers:
        - name: nocodb-app-webui
          image: nocodb/nocodb:latest
          # command: ["/bin/sh", "-c"]
          # args:
          #   - |
          #     # Construct and export DATABASE_URL using shell expansion
          #     export DATABASE_URL="postgresql://${PG_USER}:${PG_PASSWORD}@postgres-0.postgres-svc.nocodb-app.svc.cluster.local:5432/${PG_DB}"
              
          #     # Log the constructed URL (mask password in a real production log if desired)
          #     echo "Attempting to start DATABASE_URL: postgresql://${PG_USER}:********@postgres-0.postgres-svc.nocodb-app.svc.cluster.local:5432/${PG_DB}"
          #     sleep 10000
              
          env:
            # openssl rand -hex 32
            - name: DATABASE_URL
              value:  postgresql://dbadmin:Done8212@postgres-0.postgres-svc.nocodb-app.svc.cluster.local:5432/nocodb
            - name: NC_AUTH_JWT_SECRET
              value: 569a1821-0a93-45e8-87ab-eb857f20a010
            
            - name: PG_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: POSTGRES_USER
            - name: PG_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: POSTGRES_PASSWORD
            - name: PG_DB
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: POSTGRES_DB
          
          ports:
            - containerPort: 8080
              # protocol: TCP
          volumeMounts:
            - name: nocodb-claim0
              mountPath: /usr/app/data

          resources:
            requests:
              cpu: 500m
              memory: 1Gi
            limits:
              cpu: 2000m
              memory: 4Gi
          # livenessProbe:
          #   httpGet:
          #     path: /healthz
          #     port: 8080
          #   initialDelaySeconds: 120
          #   periodSeconds: 10
          #   failureThreshold: 5
          # readinessProbe:
          #   httpGet:
          #     path: /healthz
          #     port: 8080
          #   initialDelaySeconds: 90
          #   periodSeconds: 5
          #   successThreshold: 1





