apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
  namespace: redis-id
  labels:
    app: redis
data:
  redis.conf: |
    # Set a password for Redis
    # requirepass CanLoadMulti8899

    # Set the maximum memory to 256mb
    maxmemory 512mb

    # Use the allkeys-lru eviction policy when memory is full
    maxmemory-policy allkeys-lru